version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: tradia
      POSTGRES_PASSWORD: tradia
      POSTGRES_DB: tradia
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
      - mongodb
    environment:
      - DATABASE_URL=postgresql+psycopg2://tradia:tradia@postgres/tradia
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  mongo_data:
